### ISSUE TITLE
Memory allocation error on large scene with Xatlas

### ISSUE THREAD

**Issue by pedropla** [guycalledfrank/bakery-issues#123]
I get this error only if Xatlas is selected. If I use the Default atlas packer mode I don't get this error.

This is the error from .ftracelog.txt

Used host memory: 3462mb, available GPU memory: 7125mb
Launch 8x8 tiles...
Tile 0x0...
Streaming...0
npHD
Launching...
Error (1282): Memory allocation failed (Details: Function "_rtContextLaunch2D" caught exception: Memory allocation failed)

I've tried splitting it into several groups and decreasing the tile size to 256 but I still either get this error or get a Unity crash.

I still have a lot of ram (total 32gb ram + swap over 64gb). I think it might be some memory leak in xatlas as it only happens when using that.

These are my bakery settings:

![image](https://user-images.githubusercontent.com/13673481/147206365-7fa7c423-c18e-4ccd-a1b2-df6d1f50efe4.png)
![image](https://user-images.githubusercontent.com/13673481/147206420-47d592c2-b005-46ed-a060-f8a2c8e8c946.png)

I have 2 groups + the terrain which is not in a group.

The group settings are pretty similar and almost the same for both:

![image](https://user-images.githubusercontent.com/13673481/147206490-13b8e248-3694-464e-ab49-0a65f6b3c105.png)

It is hard to produce a repo scene as it only happens on a very large scene with many objects and a 2k x 2k terrain. 

I was wondering if there's a way to update the xatlas in bakery as I find a lot of the problem I have are related to it and I'm wondering if it's outdated. I do need to use it though as I want to make all the light maps grouped together on a minimal number of texture files.

**Comment by pedropla** [comment]
Looking into this further I was able to get the scene to bake if I disabled "Export Terrain Trees". With Xatlas disabled and the Default atlas packer selected I was able to export terrain trees. This might be somewhat related to the previous bug I mentioned where selecting "Export Terrain Trees" with the terrain in a bakery group and the xatlas packer selected caused it to be unable to finish exporting the scene. 

However, in this case, the terrain is not in a bakery group and it exports the scene fine, it just gives the memory error during the bakery process.

**Comment by guycalledfrank** [comment]
Hi. The error is related to VRAM, not RAM.
xatlas isn't very outdated, it just sounds like using it resulted in somewhat different atlas distribution.
"Export terrain trees" can be indeed very memory-intensive. As mentioned in the docs:

>Note that highest possible LOD level is used for every tree during baking. It is not recommended to use this option for rendering multi-kilometer forests with highly detailed models.

If the error happens when using a LMGroup on a terrain + xatlas, without any terrain trees or other objects, then it would sound suspicious and possibly a bug. Is it the case?

**Comment by pedropla** [comment]
If I disable exporting the terrain trees it works. The tree models themselves are pretty mobile optimized and a max 1k-2k tris per tree. This scene does have about 5k trees on it, but they are quite sparsely placed.

The exact error happens here:

![image](https://user-images.githubusercontent.com/13673481/147383137-e0c32208-e05d-48c5-b9b4-39ffe0bc32ec.png)

By VRAM I'm guessing you're referring to video ram of the GPU card right? If so, is there a way to have it send smaller chunks to the GPU at a time so as to allow it to still bake even if slower?

Oh, and Merry Christmas/Happy Holidays to you!

Edit: I also see in the console log that it detects that VRAM optimization is not necessary when set to auto. However, even with it forced on I still get either a memory error or a Unity crash.

![image](https://user-images.githubusercontent.com/13673481/147383222-29bf7e37-6288-45a0-8bef-24e32c00d7ef.png)

**Comment by guycalledfrank** [comment]
This is GPU memory, yes. 

> 1k-2k tris per tree. This scene does have about 5k trees on it, but they are quite sparsely placed.

That's possibly about additional 2000*5000 = 10 mil tris. Can take some memory and time, but in isolation, should be still bakeable.

One limitation with xatlas, when used as atlas packer: all atlases have to be the same size. Perhaps in your case it means more overall data, and it's just enough to overflow the VRAM. Estimated usage doesn't take geometry into account because I can't predict BVH size in advance, before the BVH is built.

How many lightmaps are in the scene? If you enable Checker Preview, it will print it to console.

...

...Merry Christmas! :)

**Comment by pedropla** [comment]
![image](https://user-images.githubusercontent.com/13673481/147401117-96742b18-c01c-4a42-bccd-9861b9edab03.png)

According to the checker setting it is only 3 lightmaps. They are all groups with a max size of 4096. The group with the terrain is the one with the trees and it only has terrain and trees so the memory footprint shouldn't be more than that. 

For some of the other groups their geometry is likely far higher than 10m tris combined but there is no memory error when rendering them.

It does give a bunch of messages about incorrect UV2 LODs for the trees but I've ignored them as the trees themselves don't have lightmaps baked for them so it shouldn't really matter right?

![image](https://user-images.githubusercontent.com/13673481/147401171-372e7427-254e-4398-97e1-9952d3fd6909.png)

Also, I've found that with the vram optimization on Force On it tends to crash Unity, with it off it runs out of memory. Not sure if that is a helpful piece of information in any way.

Let me know if you have any ideas what I can do to render.

**Comment by guycalledfrank** [comment]
Hmmm... in fact, "Lightmap count" tells the final count, while "bucket count" is a number of sub-lightmaps baked for each final lightmap. Lightmaps can be split into "buckets" if they have different LOD levels or mix terrains and regular meshes (and some other reasons). However, I only made it work with xatlas. So it gives a clue: with the default packer you have more lightmaps, because different LOD levels are in their own lightmaps; with xatlas, you have 19+12+1 = 32 intermediate full-sized lightmaps that are later fused into 3. So with xatlas it takes more VRAM to compute, but less separate maps in the end.
Seems like a large amount of baked LODs is the culprit here. Can you reuse LOD0 lightmap on other LODs? Can you use probes for some LODs?

The UV warning is irrelevant, as you guessed.

The GI VRAM opt. is no longer recommended to use: https://geom.io/bakery/wiki/index.php?title=How_do_I...#How_do_I_lightmap_a_large_world.3F

**Comment by pedropla** [comment]
A few questions to see if I can get to the bottom of this:

1) Could it be taking all the LOD levels of the trees and loading them all into memory? If so that might be the issue with the trees.

2) Is there a way to see a debug log of sorts of all the LOD levels and what meshes it is loading and processing? 

I have very few LOD groups with lightmaps enabled in the geometry below LOD1. I do have some which share some of the same geometry between LOD0 and LOD1 - for example when hiding an interior but showing the exterior on both LOD0 and LOD1. But when the geometry actually changes I've disabled lightmaps and even lightprobes on most as I'm using impostors for the majority of large LODd distant objects. So if there is a way for me to see what is being processed as a separate LOD level it might shed light on what is going wrong.

3) Is there a way to force bakery to only bake lightmaps on LOD0? I really only need lightmaps on the objects in LOD0 of LOD groups. For other levels I can either use light probes or impostors, etc.

Thanks for the info about GI VRAM Optimization, I somehow missed that page in your docs. I usually have it disabled anyway, but just enabled it to see if it would help in this case as the manual made it seem like it might be worth a try: https://geom.io/bakery/wiki/index.php?title=Manual#GI_VRAM_optimization

Also, if this is to do with LOD levels, how come it all works fine as long as trees are not enabled? Is it just a case of the memory being pushed over the edge, or could the tree export be the culprit of so many LOD levels and it using all the LOD levels of each tree?

If there's any other debugging ideas you might have for me to analyze what the memory is being used by let me know.

Thanks

**Comment by guycalledfrank** [comment]
1. Not really, only one particular LOD index buffer/lighting state is loaded at one point of time. However, LOD *vertex* buffers are shared. But the lighting state is the largest part.

Here is a little diagram I made on the forum:

![image](https://user-images.githubusercontent.com/7008423/147408658-0a772764-6012-4db7-8a31-3b11c2721954.png)


2. When the scene is exported, the temp folder is populated with many files, some of which can give you an idea (clear it first, so there are no previous bake leftovers):
- ib32.bin is the base scene index buffer. It's where all non-LODed geometry is. There are also multiple ib32_lod*.bin, each being an "addon" for the base buffer, containing geometry for each "global LOD". When baking a particular lightmap, only one addon is used.
- vbtraceTex.bin is the largest version of the vertex buffer, loaded for GI. You can check its filesize with/without the trees.

>as I'm using impostors for the majority of large LODd distant objects. 

Sounds like you should disable Contribute GI on these LODs. It will also save your runtime memory.

There is no debug view for LODs.  But you can add one line to ftBuildGraphics.cs -> MapObjectsToSceneLODs function:

![image](https://user-images.githubusercontent.com/7008423/147408981-02bbb731-fe3a-47e7-aae5-1ad4652e9153.png)

It will print used LOD object names.

3. Not currently, in fact all scene objects are collected first and then marked by the LOD level - it's trickier/slower to filter them in advance. Can you go over your prefabs and disable Contribute GI where you don't need it?

>, how come it all works fine as long as trees are not enabled? 

As the vertex buffer is shared, we have all LODs of all trees there.

**Comment by pedropla** [comment]
Thank you very much for the detailed reply. From what I see, the majority of LOD object names printed are the trees. Those seem to be the majority. Which is understandable as there are 5k trees, ha.

Regarding the other objects. One of the first things I did with impostors and other low LOD levels that use different geometry is disable GI. The reason I did that was that I am targeting mobile so I want to reduce the use of any GI or even light probes for distant objects so they can be GPU instanced. I haven't yet found any large amounts of LOD levels that use different geometry, there are only a few small places where they do but the total tris are like 10k-20k spread over all of them so it shouldn't be adding much to the memory foot print when baking.

I also looked at the frender folder. The vbtraceTex.bin is only 700mb+ and the entirety of all the ib32*.bin are a total of 1gb. Out of the 8gb in my 2080 there are around 7.5gb available for baking, so after using the 1.7gb on these buffers there should be quite a lot of working memory for the gi I'd imagine? 

I will keep investigating the issue but I'm still a bit perplexed as the numbers don't seem to add up. Of course I have a very limited understanding of the inner workings of bakery so I might be missing something.

Also, when baking with default atlas packer only one of the atlas maps is 4096 (and that one has a large unused area), most are much smaller with quite a few at 128. I'm not sure if that is at all helpful but just so you know there aren't a bunch of huge lightmaps that it needs to put together to make 3 groups.

Edit: Well there is a significant difference without trees, the vbtraceTex.bin goes down in size from 700mb+ to 290mb, less than half the size. The ib32*.bin are a total of 900mb+ without trees.

**Comment by guycalledfrank** [comment]
I tried various combinations of having static/non-static objects in the LOD group, while using xatlas + post-packing and found at least 2 inefficiences:
- Non-LOD and LOD0 rendering was split into 2 separate passes, even though it's not necessary. It would also take 2x more VRAM for GI computation of this atlas (2x of the lighting cache; geometry still takes the same).
- Post-packing code itself was called for every atlas when post-packing is enabled, even if there is only one sub-lightmap (nothing to pack really). It didn't affect VRAM, just was issuing a redundant extra step.

Fixed those: https://github.com/guycalledfrank/bakery-csharp/commit/028eb82bd676b756b9c7671df9a95b7bdc608a57

Can you try it?

>1gb. Out of the 8gb

Not that there is also the BVH size (the tree built for raytracing acceleration that resides on the GPU), and I can't predict its size in advance, but it scales with geometry.

**Comment by pedropla** [comment]
I just updated through the bakery update tool and tried and I still get the memory error at the same spot. Before I check further can I confirm if that patch is in the version pulled through the update tool or if I need to pull it differently?

**Comment by guycalledfrank** [comment]
Yeah, it reduced some VRAM usage, but seems like you're still out of it. However, you're sure you only have LOD0 marked as static, when you enabled Checker Preview, it should only say "Bucket count: 1" for every LMGroup. Bucket count > 1 means there that this group has either:
- Different baked LODs.
- Terrains and renderers together.

**Comment by guycalledfrank** [comment]
It saves some VRAM, but there is still a lot. I also checked what gets exported specifically when using terrain trees, and it looks like it's always LOD0 anyway.

The tool should work OK. You can look for "objNonOr0" in ftBuildGraphics.cs, if there is any mention of this, then it's patched.

I guess BVH for all trees is just that complex.

**Comment by pedropla** [comment]
I wonder if the BVH gets so big because of the way trees' fronds have so much transparency which requires the GPU to calculate a far more complex structure than the actual number of tris?

In any case, I guess there's not much that can be done from your end here. 

If you ever find a way to more efficiently bake a larger scene with trees, perhaps breaking it up into smaller pieces (I know that would make it difficult for shadows cast over the seams), then I would be very interested in trying it out.

**Comment by pedropla** [comment]
Actually, on second thought, I wonder why it would bake fine with texture packer set to default and fail with xatlas if it is a question of the BVH getting too big. Wouldn't that be the same size for both? And just the default texture packer would leave the textures in the original "buckets" but the xatlas would then move them to better packed combined textures? Or does the texture packer actually influence the 3D GPU calculations and BVH tree size?

**Comment by guycalledfrank** [comment]
Same size, yeah. I'm just assuming the total lightmap size is larger in your case with xatlas, so it overflows?
E,g, default packer can create atlases of different sizes, with xatlas all atlases have the same largest size (but there are fewer of them).

**Comment by pedropla** [comment]
It seems to have been that. If I merge 2 groups together and use the same size atlas (4096), it manages to bake without a problem with xatlas.
